### PR TITLE
Minor fixes

### LINKED ISSUE #205: Tags case-insensitive issue
Deleting the tag `head` will not delete the tag `Head`.
Either change the implementation to always store tags in lowercase or change the deletion to ignore case.

### LINKED ISSUE #212: Change app window size
Make Club Connect application run in fullscreen by default so that all content is easily visible. This also suppresses the need of a mouse to resize the window.

### PR DESCRIPTION
**Pull request by amrut-prabhu**
Fixes #205 
Tags and groups are always in sentence case (only first letter capitalised)

Fixes #212
Also, changed default app window to be fullscreen

### CODE REVIEW

File: src/main/java/seedu/club/model/member/Member.java [hunk 1]
```diff
@@ -184,6 +184,8 @@ public String toString() {
                 .append(getGroup())
                 .append(" Tags: ");
         getTags().forEach(builder::append);
+        builder.append(" Tasks: ");
```
Comment (yash-chowdhary) [inline src/main/java/seedu/club/model/member/Member.java]: can you remove this? There's no need to display tasks

**Review by yash-chowdhary — COMMENTED** [review]
looks good! just one change required.
